/* ParserTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. ParserTokenManager.java */
package main;
import control.erroresS;

/** Token Manager. */
@SuppressWarnings ("unused")
public class ParserTokenManager implements ParserConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1){
   switch (pos)
   {
      case 0:
         if ((active1 & 0x400000L) != 0L)
            return 26;
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 72;
            return 58;
         }
         if ((active0 & 0x3fdfffffffffff80L) != 0L)
         {
            jjmatchedKind = 62;
            return 117;
         }
         if ((active1 & 0xc0L) != 0L)
         {
            jjmatchedKind = 75;
            return 6;
         }
         return -1;
      case 1:
         if ((active0 & 0x1010000d010000L) != 0L)
            return 117;
         if ((active0 & 0x3fcfeffff2feff80L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 1;
            }
            return 117;
         }
         return -1;
      case 2:
         if ((active0 & 0x40011410400000L) != 0L)
            return 117;
         if ((active0 & 0x3f8ffeebeabeff80L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 2;
            return 117;
         }
         return -1;
      case 3:
         if ((active0 & 0x400a100060100L) != 0L)
            return 117;
         if ((active0 & 0x3f8bfe4aeab8fe80L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 3;
            return 117;
         }
         return -1;
      case 4:
         if ((active0 & 0x8080c4240000e80L) != 0L)
            return 117;
         if ((active0 & 0x3783f208aab8f000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 4;
            return 117;
         }
         return -1;
      case 5:
         if ((active0 & 0x6810208a2088000L) != 0L)
            return 117;
         if ((active0 & 0x3102f00008b07000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 5;
            return 117;
         }
         return -1;
      case 6:
         if ((active0 & 0x1100600000304000L) != 0L)
            return 117;
         if ((active0 & 0x2002900008803000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 6;
            return 117;
         }
         return -1;
      case 7:
         if ((active0 & 0x803000L) != 0L)
            return 117;
         if ((active0 & 0x2002900008000000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 7;
            return 117;
         }
         return -1;
      case 8:
         if ((active0 & 0x2000900000000000L) != 0L)
            return 117;
         if ((active0 & 0x2000008000000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 8;
            return 117;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 76);
      case 41:
         return jjStopAtPos(0, 77);
      case 43:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40L);
      case 44:
         return jjStopAtPos(0, 83);
      case 45:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80L);
      case 46:
         return jjStopAtPos(0, 84);
      case 58:
         return jjStopAtPos(0, 85);
      case 59:
         return jjStopAtPos(0, 82);
      case 61:
         return jjMoveStringLiteralDfa1_0(0x20000000000000L, 0x0L);
      case 63:
         return jjStartNfaWithStates_0(0, 86, 26);
      case 91:
         return jjStopAtPos(0, 78);
      case 93:
         return jjStopAtPos(0, 79);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x40080000000000L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x100000000000080L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x1f00L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x1e000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x1e0000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x8000000e00000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x210000f000000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x10000000000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x880000010000000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x10000000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x1e00000000000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x20000000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x6000200c0000000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x4000f00000000L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x3000000000000000L, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x3000000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0xc000000000L, 0x0L);
      case 121:
         return jjMoveStringLiteralDfa1_0(0x40000000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 80);
      case 125:
         return jjStopAtPos(0, 81);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 43:
         if ((active1 & 0x40L) != 0L)
            return jjStopAtPos(1, 70);
         break;
      case 45:
         if ((active1 & 0x80L) != 0L)
            return jjStopAtPos(1, 71);
         break;
      case 62:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStopAtPos(1, 53);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x8201000000300L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x80001003000e000L, active1, 0L);
      case 102:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(1, 24, 117);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 52, 117);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x4300000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x48000200000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x20400L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000002000000L, active1, 0L);
      case 110:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x3040100008040000L, active1, 0L);
      case 111:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(1, 16, 117);
         return jjMoveStringLiteralDfa2_0(active0, 0x100002000401800L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x4c00400000080L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x200020000000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x81000040800000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x80080000000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x180000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000800000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, 0L);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0xa0000000400L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000002000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000080L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x406180000000L);
      case 107:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000008000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x480000000000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0xa01800L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x100800000000000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000842080000L);
      case 114:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(2, 22, 117);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 36, 117);
         return jjMoveStringLiteralDfa3_0(active0, 0x200000200000000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x8020100L);
      case 116:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 40, 117);
         return jjMoveStringLiteralDfa3_0(active0, 0x108020100200L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000040000L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000000L);
      case 119:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(2, 28, 117);
         break;
      case 121:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(2, 34, 117);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 54, 117);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, 0L);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x204080L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x480000000000000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x800200L);
      case 100:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 37, 117);
         break;
      case 101:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 117);
         else if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(3, 17, 117);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 50, 117);
         return jjMoveStringLiteralDfa4_0(active0, 0x2800100840108000L);
      case 104:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 39, 117);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x200080000000000L);
      case 107:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x103044000000000L);
      case 109:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 117);
         break;
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x202080000L);
      case 115:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(3, 32, 117);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000c00L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x820088001000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x20002000L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, 0L);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x600008000000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L);
      case 100:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 42, 117);
         break;
      case 101:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 38, 117);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 51, 117);
         return jjMoveStringLiteralDfa5_0(active0, 0x182800000000000L);
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000000000L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000L);
      case 104:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 9, 117);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x1020000001000L);
      case 107:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(4, 7, 117);
         break;
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000100000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x1400000800000000L);
      case 114:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(4, 30, 117);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 59, 117);
         return jjMoveStringLiteralDfa5_0(active0, 0x100022080000L);
      case 115:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 10, 117);
         break;
      case 116:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 117);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 43, 117);
         return jjMoveStringLiteralDfa5_0(active0, 0x808000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      case 119:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(4, 33, 117);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000000L);
      case 99:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 41, 117);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 48, 117);
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      case 101:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 15, 117);
         break;
      case 102:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(5, 35, 117);
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000L);
      case 103:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 57, 117);
         return jjMoveStringLiteralDfa6_0(active0, 0x200000002000L);
      case 104:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(5, 31, 117);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000800000L);
      case 108:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 58, 117);
         return jjMoveStringLiteralDfa6_0(active0, 0x204000L);
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000000L);
      case 110:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 29, 117);
         return jjMoveStringLiteralDfa6_0(active0, 0x8001000L);
      case 114:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 55, 117);
         break;
      case 116:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(5, 19, 117);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(5, 25, 117);
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000L);
      case 119:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000000L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000L);
      case 101:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 45, 117);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 46, 117);
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000002000L);
      case 110:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 56, 117);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 60, 117);
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000000000L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L);
      case 115:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 20, 117);
         break;
      case 116:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(6, 14, 117);
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000000L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000L);
      case 121:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(6, 21, 117);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000000000L);
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(7, 12, 117);
         return jjMoveStringLiteralDfa8_0(active0, 0x2000800008000000L);
      case 110:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(7, 23, 117);
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000000L);
      case 114:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(7, 13, 117);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 100:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 47, 117);
         else if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 61, 117);
         break;
      case 101:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 44, 117);
         break;
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000L);
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 102:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(9, 27, 117);
         break;
      case 115:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 49, 117);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 117;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 117:
                  if ((0x3ff001000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(69, 70); }
                  else if (curChar == 35)
                  {
                     if (kind > 87)
                        kind = 87;
                     { jjCheckNAdd(71); }
                  }
                  if ((0x3ff001000000000L & l) != 0L)
                  {
                     if (kind > 62)
                        kind = 62;
                     { jjCheckNAdd(68); }
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(0, 11); }
                  else if ((0xac6000000000L & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                  }
                  else if ((0x5000000000000000L & l) != 0L)
                  {
                     if (kind > 73)
                        kind = 73;
                  }
                  else if (curChar == 39)
                  {
                     if (kind > 87)
                        kind = 87;
                     { jjCheckNAddStates(12, 15); }
                  }
                  else if (curChar == 34)
                  {
                     if (kind > 87)
                        kind = 87;
                     { jjCheckNAddStates(16, 19); }
                  }
                  else if (curChar == 36)
                  {
                     if (kind > 62)
                        kind = 62;
                     { jjCheckNAddStates(20, 22); }
                  }
                  else if (curChar == 33)
                     { jjCheckNAddTwoStates(60, 57); }
                  else if (curChar == 61)
                     { jjCheckNAddTwoStates(58, 57); }
                  else if (curChar == 63)
                     { jjCheckNAdd(26); }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 68)
                        kind = 68;
                     { jjCheckNAddStates(23, 29); }
                  }
                  else if (curChar == 42)
                     { jjCheckNAddStates(30, 32); }
                  else if (curChar == 60)
                     { jjCheckNAddTwoStates(57, 113); }
                  else if (curChar == 62)
                     { jjCheckNAddStates(33, 35); }
                  else if (curChar == 48)
                  {
                     if (kind > 68)
                        kind = 68;
                     { jjCheckNAddStates(36, 41); }
                  }
                  else if (curChar == 47)
                     { jjCheckNAddTwoStates(62, 6); }
                  else if (curChar == 33)
                  {
                     if (kind > 74)
                        kind = 74;
                  }
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 12;
                  else if (curChar == 61)
                  {
                     if (kind > 72)
                        kind = 72;
                  }
                  else if (curChar == 37)
                     { jjCheckNAdd(6); }
                  else if (curChar == 45)
                     { jjCheckNAdd(6); }
                  else if (curChar == 43)
                     { jjCheckNAdd(6); }
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 58:
                  if (curChar == 61)
                  {
                     if (kind > 73)
                        kind = 73;
                  }
                  if (curChar == 61)
                     { jjCheckNAdd(57); }
                  break;
               case 1:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(2, 3); }
                  break;
               case 2:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(2, 3); }
                  break;
               case 3:
                  if (curChar == 42)
                     { jjAddStates(42, 43); }
                  break;
               case 4:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(2, 3); }
                  break;
               case 5:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 6:
                  if (curChar == 61 && kind > 72)
                     kind = 72;
                  break;
               case 7:
                  if (curChar == 43)
                     { jjCheckNAdd(6); }
                  break;
               case 8:
                  if (curChar == 45)
                     { jjCheckNAdd(6); }
                  break;
               case 9:
                  if (curChar == 37)
                     { jjCheckNAdd(6); }
                  break;
               case 10:
                  if (curChar == 61 && kind > 72)
                     kind = 72;
                  break;
               case 11:
                  if ((0x5000000000000000L & l) != 0L && kind > 73)
                     kind = 73;
                  break;
               case 12:
                  if (curChar == 38 && kind > 74)
                     kind = 74;
                  break;
               case 13:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 16:
                  if (curChar == 33 && kind > 74)
                     kind = 74;
                  break;
               case 17:
                  if ((0xac6000000000L & l) != 0L && kind > 75)
                     kind = 75;
                  break;
               case 19:
                  if (curChar == 36)
                     { jjCheckNAddTwoStates(20, 21); }
                  break;
               case 20:
                  if ((0x3ff001000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(20, 21); }
                  break;
               case 23:
                  if (curChar != 36)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(24); }
                  break;
               case 24:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(24); }
                  break;
               case 25:
                  if (curChar == 63)
                     { jjCheckNAdd(26); }
                  break;
               case 26:
                  if (curChar != 63)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(26); }
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(0, 11); }
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(28, 29); }
                  break;
               case 30:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(31); }
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(31, 32); }
                  break;
               case 32:
                  if (curChar == 46)
                     { jjCheckNAdd(33); }
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(33); }
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(34, 35); }
                  break;
               case 35:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 36:
                  if (curChar != 36)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(37); }
                  break;
               case 37:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(37); }
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(38, 39); }
                  break;
               case 39:
                  if (curChar == 46)
                     { jjCheckNAddTwoStates(40, 41); }
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(40, 41); }
                  break;
               case 41:
                  if ((0x500000000000L & l) != 0L)
                     { jjCheckNAdd(42); }
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(42); }
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 44:
                  if (curChar != 36)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(45); }
                  break;
               case 45:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(45); }
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(46, 47); }
                  break;
               case 47:
                  if (curChar == 46)
                     { jjCheckNAddTwoStates(48, 49); }
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(48, 49); }
                  break;
               case 49:
                  if (curChar == 46)
                     { jjCheckNAdd(50); }
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAddTwoStates(49, 50); }
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(51, 52); }
                  break;
               case 52:
                  if (curChar == 46)
                     { jjCheckNAdd(53); }
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(53, 54); }
                  break;
               case 54:
                  if ((0xac0000000000L & l) != 0L)
                     { jjCheckNAdd(55); }
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(55); }
                  break;
               case 56:
                  if (curChar == 61)
                     { jjCheckNAddTwoStates(58, 57); }
                  break;
               case 57:
                  if (curChar == 61 && kind > 73)
                     kind = 73;
                  break;
               case 59:
                  if (curChar == 33)
                     { jjCheckNAddTwoStates(60, 57); }
                  break;
               case 60:
                  if (curChar == 61)
                     { jjCheckNAdd(57); }
                  break;
               case 61:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(62, 6); }
                  break;
               case 62:
                  if (curChar != 47)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAddStates(44, 46); }
                  break;
               case 63:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAddStates(44, 46); }
                  break;
               case 64:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 65:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 67:
                  if (curChar != 36)
                     break;
                  if (kind > 62)
                     kind = 62;
                  { jjCheckNAddStates(20, 22); }
                  break;
               case 68:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  { jjCheckNAdd(68); }
                  break;
               case 69:
                  if ((0x3ff001000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(69, 70); }
                  break;
               case 70:
                  if (curChar != 35)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(71); }
                  break;
               case 71:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(71); }
                  break;
               case 72:
                  if (curChar != 48)
                     break;
                  if (kind > 68)
                     kind = 68;
                  { jjCheckNAddStates(36, 41); }
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 79:
                  if (curChar == 46)
                     { jjCheckNAdd(80); }
                  break;
               case 80:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(80, 81); }
                  break;
               case 82:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(83); }
                  break;
               case 83:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAdd(83); }
                  break;
               case 84:
                  if (curChar == 46)
                     { jjCheckNAdd(85); }
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAdd(85); }
                  break;
               case 86:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 68)
                     kind = 68;
                  { jjCheckNAddStates(23, 29); }
                  break;
               case 87:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(87, 79); }
                  break;
               case 88:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(88, 81); }
                  break;
               case 89:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(89, 84); }
                  break;
               case 90:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 68)
                     kind = 68;
                  { jjCheckNAdd(90); }
                  break;
               case 91:
                  if (curChar != 34)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAddStates(16, 19); }
                  break;
               case 93:
                  { jjCheckNAddStates(47, 49); }
                  break;
               case 94:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddStates(47, 49); }
                  break;
               case 95:
                  if (curChar == 34 && kind > 69)
                     kind = 69;
                  break;
               case 96:
                  if ((0xfffffffbffffdbffL & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(96); }
                  break;
               case 97:
                  if (curChar != 39)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAddStates(12, 15); }
                  break;
               case 99:
                  { jjCheckNAddStates(50, 52); }
                  break;
               case 100:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     { jjCheckNAddStates(50, 52); }
                  break;
               case 101:
                  if (curChar == 39 && kind > 69)
                     kind = 69;
                  break;
               case 102:
                  if ((0xffffff7fffffdbffL & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(102); }
                  break;
               case 105:
               case 106:
                  { jjCheckNAddStates(53, 55); }
                  break;
               case 108:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 109:
                  if (curChar == 62)
                     { jjCheckNAddStates(33, 35); }
                  break;
               case 110:
                  if (curChar == 62 && kind > 75)
                     kind = 75;
                  break;
               case 111:
                  if (curChar == 62)
                     { jjCheckNAdd(110); }
                  break;
               case 112:
                  if (curChar == 60)
                     { jjCheckNAddTwoStates(57, 113); }
                  break;
               case 113:
                  if (curChar == 60 && kind > 75)
                     kind = 75;
                  break;
               case 114:
                  if (curChar == 42)
                     { jjCheckNAddStates(30, 32); }
                  break;
               case 115:
                  if (curChar == 42)
                     { jjCheckNAdd(6); }
                  break;
               case 116:
                  if (curChar == 42 && kind > 75)
                     kind = 75;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 117:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(69, 70); }
                  else if (curChar == 64)
                  {
                     if (kind > 87)
                        kind = 87;
                     { jjCheckNAdd(71); }
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 62)
                        kind = 62;
                     { jjCheckNAdd(68); }
                  }
                  break;
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 62)
                        kind = 62;
                     { jjCheckNAddStates(20, 22); }
                  }
                  else if ((0x5000000040000000L & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                  }
                  else if (curChar == 96)
                  {
                     if (kind > 87)
                        kind = 87;
                     { jjCheckNAddStates(56, 59); }
                  }
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 23;
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 19;
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 2:
               case 4:
                  { jjCheckNAddTwoStates(2, 3); }
                  break;
               case 14:
                  if (curChar == 124 && kind > 74)
                     kind = 74;
                  break;
               case 15:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 17:
                  if ((0x5000000040000000L & l) != 0L && kind > 75)
                     kind = 75;
                  break;
               case 18:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
               case 20:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(20, 21); }
                  break;
               case 21:
                  if (curChar == 124 && kind > 87)
                     kind = 87;
                  break;
               case 22:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 23:
               case 24:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(24); }
                  break;
               case 29:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(60, 61); }
                  break;
               case 36:
               case 37:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(37); }
                  break;
               case 44:
               case 45:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(45); }
                  break;
               case 63:
                  if (kind > 5)
                     kind = 5;
                  { jjAddStates(44, 46); }
                  break;
               case 67:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  { jjCheckNAddStates(20, 22); }
                  break;
               case 68:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  { jjCheckNAdd(68); }
                  break;
               case 69:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(69, 70); }
                  break;
               case 70:
                  if (curChar != 64)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(71); }
                  break;
               case 71:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(71); }
                  break;
               case 73:
                  if ((0x100000001000000L & l) != 0L)
                     { jjCheckNAdd(74); }
                  break;
               case 74:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  { jjCheckNAdd(74); }
                  break;
               case 75:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 77:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 81:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(62, 63); }
                  break;
               case 92:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 93:
                  { jjCheckNAddStates(47, 49); }
                  break;
               case 94:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(47, 49); }
                  break;
               case 96:
                  if (kind > 87)
                     kind = 87;
                  jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 99:
                  { jjCheckNAddStates(50, 52); }
                  break;
               case 100:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(50, 52); }
                  break;
               case 102:
                  if (kind > 87)
                     kind = 87;
                  jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 103:
                  if (curChar != 96)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAddStates(56, 59); }
                  break;
               case 104:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 105:
                  { jjCheckNAddStates(53, 55); }
                  break;
               case 106:
                  if ((0xfffffffeefffffffL & l) != 0L)
                     { jjCheckNAddStates(53, 55); }
                  break;
               case 107:
                  if (curChar == 96 && kind > 69)
                     kind = 69;
                  break;
               case 108:
                  if ((0xfffffffeffffffffL & l) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  { jjCheckNAdd(108); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
               case 4:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(2, 3); }
                  break;
               case 63:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjAddStates(44, 46); }
                  break;
               case 93:
               case 94:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(47, 49); }
                  break;
               case 96:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 99:
               case 100:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(50, 52); }
                  break;
               case 102:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 105:
               case 106:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(53, 55); }
                  break;
               case 108:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 87)
                     kind = 87;
                  jjstateSet[jjnewStateCnt++] = 108;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 117 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\142\162\145\141\153", 
"\143\141\163\145", "\143\141\164\143\150", "\143\154\141\163\163", "\143\157\156\163\164", 
"\143\157\156\164\151\156\165\145", "\144\145\142\165\147\147\145\162", "\144\145\146\141\165\154\164", 
"\144\145\154\145\164\145", "\144\157", "\145\154\163\145", "\145\156\165\155", 
"\145\170\160\157\162\164", "\145\170\164\145\156\144\163", "\146\151\156\141\154\154\171", 
"\146\157\162", "\146\165\156\143\164\151\157\156", "\151\146", "\151\155\160\157\162\164", 
"\151\156", "\151\156\163\164\141\156\143\145\157\146", "\156\145\167", 
"\162\145\164\165\162\156", "\163\165\160\145\162", "\163\167\151\164\143\150", "\164\150\151\163", 
"\164\150\162\157\167", "\164\162\171", "\164\171\160\145\157\146", "\166\141\162", 
"\166\157\151\144", "\167\150\151\154\145", "\167\151\164\150", "\154\145\164", 
"\163\164\141\164\151\143", "\171\151\145\154\144", "\141\167\141\151\164", 
"\151\156\164\145\162\146\141\143\145", "\160\141\143\153\141\147\145", "\160\162\151\166\141\164\145", 
"\160\162\157\164\145\143\164\145\144", "\160\165\142\154\151\143", "\151\155\160\154\145\155\145\156\164\163", 
"\164\162\165\145", "\146\141\154\163\145", "\157\146", "\75\76", "\141\156\171", 
"\156\165\155\142\145\162", "\142\157\157\154\145\141\156", "\163\164\162\151\156\147", 
"\163\171\155\142\157\154", "\156\145\166\145\162", "\165\156\153\156\157\167\156", 
"\165\156\144\145\146\151\156\145\144", null, null, null, null, null, null, null, null, "\53\53", "\55\55", null, null, 
null, null, "\50", "\51", "\133", "\135", "\173", "\175", "\73", "\54", "\56", 
"\72", "\77", null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   28, 29, 34, 35, 38, 39, 43, 44, 46, 47, 51, 52, 98, 100, 101, 102, 
   92, 94, 95, 96, 68, 69, 70, 87, 79, 88, 81, 89, 84, 90, 115, 6, 
   116, 57, 111, 110, 73, 75, 77, 79, 81, 84, 4, 5, 63, 65, 66, 92, 
   94, 95, 98, 100, 101, 104, 106, 107, 104, 106, 107, 108, 30, 31, 82, 83, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public ParserTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public ParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 117; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffffff81L, 0xffffffL, 
};
static final long[] jjtoSkip = {
   0x7eL, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[117];
    private final int[] jjstateSet = new int[2 * 117];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
