/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package main;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_LINEA = 5;
  /** RegularExpression Id. */
  int COMENTARIO_BLOQUE = 6;
  /** RegularExpression Id. */
  int BREAK = 7;
  /** RegularExpression Id. */
  int CASE = 8;
  /** RegularExpression Id. */
  int CATCH = 9;
  /** RegularExpression Id. */
  int CLASS = 10;
  /** RegularExpression Id. */
  int CONST = 11;
  /** RegularExpression Id. */
  int CONTINUE = 12;
  /** RegularExpression Id. */
  int DEBUGGER = 13;
  /** RegularExpression Id. */
  int DEFA = 14;
  /** RegularExpression Id. */
  int DELETE = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int ENUM = 18;
  /** RegularExpression Id. */
  int EXPORT = 19;
  /** RegularExpression Id. */
  int EXTENDS = 20;
  /** RegularExpression Id. */
  int FINALLY = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int FUNCTION = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int IMPORT = 25;
  /** RegularExpression Id. */
  int IN = 26;
  /** RegularExpression Id. */
  int INSTANCEOF = 27;
  /** RegularExpression Id. */
  int NEW = 28;
  /** RegularExpression Id. */
  int RETURN = 29;
  /** RegularExpression Id. */
  int SUPER = 30;
  /** RegularExpression Id. */
  int SWITCH = 31;
  /** RegularExpression Id. */
  int THIS = 32;
  /** RegularExpression Id. */
  int THROW = 33;
  /** RegularExpression Id. */
  int TRY = 34;
  /** RegularExpression Id. */
  int TYPEOF = 35;
  /** RegularExpression Id. */
  int VAR = 36;
  /** RegularExpression Id. */
  int VOID = 37;
  /** RegularExpression Id. */
  int WHILE = 38;
  /** RegularExpression Id. */
  int WITH = 39;
  /** RegularExpression Id. */
  int LET = 40;
  /** RegularExpression Id. */
  int STATIC = 41;
  /** RegularExpression Id. */
  int YIELD = 42;
  /** RegularExpression Id. */
  int AWAIT = 43;
  /** RegularExpression Id. */
  int INTERFACE = 44;
  /** RegularExpression Id. */
  int PACKAGE = 45;
  /** RegularExpression Id. */
  int PRIVATE = 46;
  /** RegularExpression Id. */
  int PROTECTED = 47;
  /** RegularExpression Id. */
  int PUBLIC = 48;
  /** RegularExpression Id. */
  int IMPLEMENTS = 49;
  /** RegularExpression Id. */
  int TRUE = 50;
  /** RegularExpression Id. */
  int FALSE = 51;
  /** RegularExpression Id. */
  int OF = 52;
  /** RegularExpression Id. */
  int FLECHA = 53;
  /** RegularExpression Id. */
  int TIPO_ANY = 54;
  /** RegularExpression Id. */
  int TIPO_NUMBER = 55;
  /** RegularExpression Id. */
  int TIPO_BOOLEAN = 56;
  /** RegularExpression Id. */
  int TIPO_STRING = 57;
  /** RegularExpression Id. */
  int TIPO_SYMBOL = 58;
  /** RegularExpression Id. */
  int TIPO_NEVER = 59;
  /** RegularExpression Id. */
  int TIPO_UNKNOWN = 60;
  /** RegularExpression Id. */
  int TIPO_UNDEFINED = 61;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 62;
  /** RegularExpression Id. */
  int HEXADECIMAL = 63;
  /** RegularExpression Id. */
  int BINARIO = 64;
  /** RegularExpression Id. */
  int OCTAL = 65;
  /** RegularExpression Id. */
  int EXPONENCIAL = 66;
  /** RegularExpression Id. */
  int DECIMAL = 67;
  /** RegularExpression Id. */
  int ENTERO = 68;
  /** RegularExpression Id. */
  int CADENA = 69;
  /** RegularExpression Id. */
  int INCREMENTO = 70;
  /** RegularExpression Id. */
  int DECREMENTO = 71;
  /** RegularExpression Id. */
  int OPERADOR_ASIGNACION = 72;
  /** RegularExpression Id. */
  int OPERADOR_COMPARACION = 73;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO = 74;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO = 75;
  /** RegularExpression Id. */
  int PARENTESIS_APERTURA = 76;
  /** RegularExpression Id. */
  int PARENTESIS_CIERRE = 77;
  /** RegularExpression Id. */
  int CORCHETE_APERTURA = 78;
  /** RegularExpression Id. */
  int CORCHETE_CIERRE = 79;
  /** RegularExpression Id. */
  int LLAVE_APERTURA = 80;
  /** RegularExpression Id. */
  int LLAVE_CIERRE = 81;
  /** RegularExpression Id. */
  int PUNTO_Y_COMA = 82;
  /** RegularExpression Id. */
  int COMA = 83;
  /** RegularExpression Id. */
  int PUNTO = 84;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 85;
  /** RegularExpression Id. */
  int INTERROGACION = 86;
  /** RegularExpression Id. */
  int ERROR_LEXICO = 87;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<COMENTARIO_LINEA>",
    "<COMENTARIO_BLOQUE>",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"debugger\"",
    "\"default\"",
    "\"delete\"",
    "\"do\"",
    "\"else\"",
    "\"enum\"",
    "\"export\"",
    "\"extends\"",
    "\"finally\"",
    "\"for\"",
    "\"function\"",
    "\"if\"",
    "\"import\"",
    "\"in\"",
    "\"instanceof\"",
    "\"new\"",
    "\"return\"",
    "\"super\"",
    "\"switch\"",
    "\"this\"",
    "\"throw\"",
    "\"try\"",
    "\"typeof\"",
    "\"var\"",
    "\"void\"",
    "\"while\"",
    "\"with\"",
    "\"let\"",
    "\"static\"",
    "\"yield\"",
    "\"await\"",
    "\"interface\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"implements\"",
    "\"true\"",
    "\"false\"",
    "\"of\"",
    "\"=>\"",
    "\"any\"",
    "\"number\"",
    "\"boolean\"",
    "\"string\"",
    "\"symbol\"",
    "\"never\"",
    "\"unknown\"",
    "\"undefined\"",
    "<IDENTIFICADOR>",
    "<HEXADECIMAL>",
    "<BINARIO>",
    "<OCTAL>",
    "<EXPONENCIAL>",
    "<DECIMAL>",
    "<ENTERO>",
    "<CADENA>",
    "\"++\"",
    "\"--\"",
    "<OPERADOR_ASIGNACION>",
    "<OPERADOR_COMPARACION>",
    "<OPERADOR_LOGICO>",
    "<OPERADOR_ARITMETICO>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"?\"",
    "<ERROR_LEXICO>",
  };

}
