/* Parser.java */
/* Generated By:JavaCC: Do not edit this line. Parser.java */
package main;
import control.erroresS;

@SuppressWarnings("all")
public class Parser implements ParserConstants {

    public java.util.List<String[]> erroresSintacticos =
            new java.util.ArrayList<>();

private void registrarError(ParseException e) {
  Token encontrado = getToken(1);
  int linea = encontrado != null ? encontrado.beginLine : -1;
  int columna = encontrado != null ? encontrado.beginColumn : -1;
  String lexema = encontrado != null ? encontrado.image : "fin de archivo";
  erroresSintacticos.add(new String[]{String.valueOf(linea), String.valueOf(columna),
      lexema, erroresS.tokensEsperados(e), erroresS.descripcionAmigable(e, encontrado)});
}

private void recuperarError(ParseException e) {
  registrarError(e);
  Token anterior = getToken(1);

    Token siguiente = getToken(1);
    while (siguiente.kind != EOF
            && siguiente.kind != PUNTO_Y_COMA
            && siguiente.kind != LET
            && siguiente.kind != CONST
            && siguiente.kind != VAR
            && siguiente.kind != IF
            && siguiente.kind != FOR
            && siguiente.kind != FUNCTION
            && siguiente.kind != WHILE
            && siguiente.kind != LLAVE_APERTURA
            && siguiente.kind != LLAVE_CIERRE) {
        getNextToken();
        siguiente = getToken(1);
    }

    if (siguiente.kind == PUNTO_Y_COMA) {
        getNextToken();
    } else if (siguiente.kind == LLAVE_CIERRE) {
        getNextToken();
    }
    if (getToken(1) == anterior && getToken(1).kind != EOF) {
      getNextToken();
    }
}

private boolean siguienteEsFlecha() {
  if (getToken(1).kind != PARENTESIS_APERTURA) return false;
  int profundidad = 0;
  for (int posicion = 1; posicion < 256; posicion++) {
    int kind = getToken(posicion).kind;
    if (kind == PARENTESIS_APERTURA) profundidad++;
    if (kind == PARENTESIS_CIERRE) {
      profundidad--;
      if (profundidad == 0) {
        for (int despues = posicion + 1; despues < 256; despues++) {
          int siguiente = getToken(despues).kind;
          if (siguiente == FLECHA) return true;
          if (siguiente == PUNTO_Y_COMA || siguiente == LLAVE_APERTURA
              || siguiente == LLAVE_CIERRE || siguiente == EOF) return false;
        }
        return false;
      }
    }
    if (kind == EOF) return false;
  }
  return false;
}

private boolean siguienteEsForOf() {
  for (int posicion = 1; posicion < 256; posicion++) {
    int kind = getToken(posicion).kind;
    if (kind == OF || kind == IN) return true;
    if (kind == PUNTO_Y_COMA || kind == PARENTESIS_CIERRE || kind == EOF) return false;
  }
  return false;
}

  public static String descripcionErrorLexico(Token token) {
    if (token != null && token.image != null
          && token.image.matches("([0-9]+\\.[0-9]*([\\.,][0-9]+)+|[0-9]+[eE][+-]?[0-9]+\\.[0-9]+|[0-9]+\\.[0-9]+(\\*|/|\\+|-)[0-9]+|[0-9]+\\.\\.[0-9]+)")) {
      return "N\u00famero mal formado.";
    }
    if (token != null && token.image != null
        && (token.image.startsWith("\"") || token.image.startsWith("'")
            || token.image.startsWith("`"))) {
      return "Cadena sin cerrar.";
    }
    if (token != null && token.image != null && token.image.matches("[0-9].*")) {
      return "N\u00famero mal formado.";
    }
    if (token != null && token.image != null
        && token.image.matches("[A-Za-z_$][A-Za-z0-9_$]*(#|[+*/%=&|^~<>!?-])[A-Za-z0-9_$#]*")) {
      return "Identificador o palabra reservada mal formada.";
    }
    return "S\u00edmbolo no reconocido.";
  }

  final public void Inicio() throws ParseException {
Token anterior;
        while (getToken(1).kind != EOF) {
            anterior = getToken(1);
            try {
                Instruccion();
            } catch (ParseException e) {
                recuperarError(e);
            }
            // Seguro anti-bucle infinito: si tras un intento completo
            // (parseo + recuperación) seguimos exactamente en el mismo token,
            // forzamos avanzar uno para garantizar progreso siempre.
            if (getToken(1) == anterior && getToken(1).kind != EOF) {
                getNextToken();
            }
        }
    jj_consume_token(0);
}

  final public void VariableDeclaracion() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LET:{
      jj_consume_token(LET);
      break;
      }
    case CONST:{
      jj_consume_token(CONST);
      break;
      }
    case VAR:{
      jj_consume_token(VAR);
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(IDENTIFICADOR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTERROGACION:{
      jj_consume_token(INTERROGACION);
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DOS_PUNTOS:{
      jj_consume_token(DOS_PUNTOS);
      Tipo();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPERADOR_ASIGNACION:{
      jj_consume_token(OPERADOR_ASIGNACION);
      Expresion();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PUNTO_Y_COMA:{
      jj_consume_token(PUNTO_Y_COMA);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
}

  final public void Tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VOID:
    case TIPO_ANY:
    case TIPO_NUMBER:
    case TIPO_BOOLEAN:
    case TIPO_STRING:
    case TIPO_NEVER:
    case TIPO_UNKNOWN:
    case TIPO_UNDEFINED:
    case IDENTIFICADOR:{
      TipoBase();
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CORCHETE_APERTURA:{
          ;
          break;
          }
        default:
          jj_la1[5] = jj_gen;
          break label_1;
        }
        jj_consume_token(CORCHETE_APERTURA);
        jj_consume_token(CORCHETE_CIERRE);
      }
      break;
      }
    case CORCHETE_APERTURA:{
      jj_consume_token(CORCHETE_APERTURA);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VOID:
      case TIPO_ANY:
      case TIPO_NUMBER:
      case TIPO_BOOLEAN:
      case TIPO_STRING:
      case TIPO_NEVER:
      case TIPO_UNKNOWN:
      case TIPO_UNDEFINED:
      case IDENTIFICADOR:
      case CORCHETE_APERTURA:{
        Tipo();
        label_2:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMA:{
            ;
            break;
            }
          default:
            jj_la1[6] = jj_gen;
            break label_2;
          }
          jj_consume_token(COMA);
          Tipo();
        }
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        ;
      }
      jj_consume_token(CORCHETE_CIERRE);
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void TipoBase() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_NUMBER:{
      jj_consume_token(TIPO_NUMBER);
      break;
      }
    case TIPO_STRING:{
      jj_consume_token(TIPO_STRING);
      break;
      }
    case TIPO_BOOLEAN:{
      jj_consume_token(TIPO_BOOLEAN);
      break;
      }
    case TIPO_ANY:{
      jj_consume_token(TIPO_ANY);
      break;
      }
    case TIPO_UNKNOWN:{
      jj_consume_token(TIPO_UNKNOWN);
      break;
      }
    case TIPO_NEVER:{
      jj_consume_token(TIPO_NEVER);
      break;
      }
    case TIPO_UNDEFINED:{
      jj_consume_token(TIPO_UNDEFINED);
      break;
      }
    case VOID:{
      jj_consume_token(VOID);
      break;
      }
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void Expresion() throws ParseException {
    ExpresionAsignacion();
}

  final public void ExpresionAsignacion() throws ParseException {
    ExpresionTernaria();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPERADOR_ASIGNACION:{
      jj_consume_token(OPERADOR_ASIGNACION);
      ExpresionAsignacion();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
}

  final public void ExpresionTernaria() throws ParseException {
    ExpresionLogica();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTERROGACION:{
      jj_consume_token(INTERROGACION);
      Expresion();
      jj_consume_token(DOS_PUNTOS);
      Expresion();
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
}

  final public void ExpresionLogica() throws ParseException {
    ExpresionRelacional();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPERADOR_LOGICO:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_3;
      }
      jj_consume_token(OPERADOR_LOGICO);
      ExpresionRelacional();
    }
}

  final public void ExpresionRelacional() throws ParseException {
    ExpresionAritmetica();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPERADOR_COMPARACION:{
        ;
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        break label_4;
      }
      jj_consume_token(OPERADOR_COMPARACION);
      ExpresionAritmetica();
    }
}

  final public void ExpresionAritmetica() throws ParseException {
    Factor();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPERADOR_ARITMETICO:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_5;
      }
      jj_consume_token(OPERADOR_ARITMETICO);
      Factor();
    }
}

  final public void Factor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPERADOR_LOGICO:
    case OPERADOR_ARITMETICO:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPERADOR_LOGICO:{
        jj_consume_token(OPERADOR_LOGICO);
        break;
        }
      case OPERADOR_ARITMETICO:{
        jj_consume_token(OPERADOR_ARITMETICO);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    Valor();
}

  final public void Valor() throws ParseException {
    if (siguienteEsFlecha()) {
      FlechaFuncion();
    } else if (jj_2_1(3)) {
      jj_consume_token(IDENTIFICADOR);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INTERROGACION:{
        jj_consume_token(INTERROGACION);
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOS_PUNTOS:{
        jj_consume_token(DOS_PUNTOS);
        Tipo();
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        ;
      }
      jj_consume_token(FLECHA);
      Expresion();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TRUE:
      case FALSE:
      case IDENTIFICADOR:
      case HEXADECIMAL:
      case BINARIO:
      case OCTAL:
      case EXPONENCIAL:
      case DECIMAL:
      case ENTERO:
      case CADENA:
      case PARENTESIS_APERTURA:
      case CORCHETE_APERTURA:
      case LLAVE_APERTURA:{
        Primario();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INCREMENTO:
        case DECREMENTO:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case INCREMENTO:{
            jj_consume_token(INCREMENTO);
            break;
            }
          case DECREMENTO:{
            jj_consume_token(DECREMENTO);
            break;
            }
          default:
            jj_la1[19] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
          }
        default:
          jj_la1[20] = jj_gen;
          ;
        }
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void Primario() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PARENTESIS_APERTURA:
        case CORCHETE_APERTURA:
        case PUNTO:{
          ;
          break;
          }
        default:
          jj_la1[22] = jj_gen;
          break label_6;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PUNTO:{
          jj_consume_token(PUNTO);
          jj_consume_token(IDENTIFICADOR);
          break;
          }
        case PARENTESIS_APERTURA:{
          LlamadaArgumentos();
          break;
          }
        case CORCHETE_APERTURA:{
          AccesoArreglo();
          break;
          }
        default:
          jj_la1[23] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      break;
      }
    case ENTERO:{
      jj_consume_token(ENTERO);
      break;
      }
    case DECIMAL:{
      jj_consume_token(DECIMAL);
      break;
      }
    case EXPONENCIAL:{
      jj_consume_token(EXPONENCIAL);
      break;
      }
    case HEXADECIMAL:{
      jj_consume_token(HEXADECIMAL);
      break;
      }
    case BINARIO:{
      jj_consume_token(BINARIO);
      break;
      }
    case OCTAL:{
      jj_consume_token(OCTAL);
      break;
      }
    case CADENA:{
      jj_consume_token(CADENA);
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
      break;
      }
    case CORCHETE_APERTURA:{
      ArregloLiteral();
      break;
      }
    case LLAVE_APERTURA:{
      ObjetoLiteral();
      break;
      }
    case PARENTESIS_APERTURA:{
      jj_consume_token(PARENTESIS_APERTURA);
      Expresion();
      jj_consume_token(PARENTESIS_CIERRE);
      break;
      }
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void LlamadaArgumentos() throws ParseException {
    jj_consume_token(PARENTESIS_APERTURA);
    if (jj_2_2(1)) {
      Expresion();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMA:{
          ;
          break;
          }
        default:
          jj_la1[25] = jj_gen;
          break label_7;
        }
        jj_consume_token(COMA);
        Expresion();
      }
    } else {
      ;
    }
    jj_consume_token(PARENTESIS_CIERRE);
}

  final public void AccesoArreglo() throws ParseException {
    jj_consume_token(CORCHETE_APERTURA);
    Expresion();
    jj_consume_token(CORCHETE_CIERRE);
}

  final public void ArregloLiteral() throws ParseException {
    jj_consume_token(CORCHETE_APERTURA);
    if (jj_2_3(1)) {
      Expresion();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMA:{
          ;
          break;
          }
        default:
          jj_la1[26] = jj_gen;
          break label_8;
        }
        jj_consume_token(COMA);
        Expresion();
      }
    } else {
      ;
    }
    jj_consume_token(CORCHETE_CIERRE);
}

  final public void ObjetoLiteral() throws ParseException {
    jj_consume_token(LLAVE_APERTURA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:
    case CADENA:{
      PropiedadObjeto();
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMA:{
          ;
          break;
          }
        default:
          jj_la1[27] = jj_gen;
          break label_9;
        }
        jj_consume_token(COMA);
        PropiedadObjeto();
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMA:{
        jj_consume_token(COMA);
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    jj_consume_token(LLAVE_CIERRE);
}

  final public void PropiedadObjeto() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
      break;
      }
    case CADENA:{
      jj_consume_token(CADENA);
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DOS_PUNTOS:{
      jj_consume_token(DOS_PUNTOS);
      Expresion();
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      ;
    }
}

  final public void FlechaFuncion() throws ParseException {
    jj_consume_token(PARENTESIS_APERTURA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      Parametro();
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMA:{
          ;
          break;
          }
        default:
          jj_la1[32] = jj_gen;
          break label_10;
        }
        jj_consume_token(COMA);
        Parametro();
      }
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      ;
    }
    jj_consume_token(PARENTESIS_CIERRE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DOS_PUNTOS:{
      jj_consume_token(DOS_PUNTOS);
      Tipo();
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      ;
    }
    jj_consume_token(FLECHA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LLAVE_APERTURA:{
      Bloque();
      break;
      }
    default:
      jj_la1[35] = jj_gen;
      if (jj_2_4(1)) {
        Expresion();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void Parametro() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTERROGACION:{
      jj_consume_token(INTERROGACION);
      break;
      }
    default:
      jj_la1[36] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DOS_PUNTOS:{
      jj_consume_token(DOS_PUNTOS);
      Tipo();
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      ;
    }
}

  final public void Instruccion() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case CONST:
    case VAR:
    case LET:{
      Declaracion();
      break;
      }
    case FUNCTION:{
      FuncionDeclaracion();
      break;
      }
    case FOR:
    case IF:
    case RETURN:
    case WHILE:
    case IDENTIFICADOR:
    case LLAVE_APERTURA:{
      Sentencia();
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void Declaracion() throws ParseException {
    VariableDeclaracion();
}

  final public void Asignacion() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUNTO:{
        ;
        break;
        }
      default:
        jj_la1[39] = jj_gen;
        break label_11;
      }
      jj_consume_token(PUNTO);
      jj_consume_token(IDENTIFICADOR);
    }
    jj_consume_token(OPERADOR_ASIGNACION);
    Expresion();
    jj_consume_token(PUNTO_Y_COMA);
}

  final public void Sentencia() throws ParseException {
    if (jj_2_5(5)) {
      Asignacion();
    } else if (jj_2_6(3)) {
      IncrementoSentencia();
    } else if (jj_2_7(4)) {
      LlamadaFuncion();
      jj_consume_token(PUNTO_Y_COMA);
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:{
        IfSentencia();
        break;
        }
      case FOR:{
        ForSentencia();
        break;
        }
      case WHILE:{
        WhileSentencia();
        break;
        }
      case RETURN:{
        ReturnSentencia();
        break;
        }
      case LLAVE_APERTURA:{
        Bloque();
        break;
        }
      default:
        jj_la1[40] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void IncrementoSentencia() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INCREMENTO:{
      jj_consume_token(INCREMENTO);
      break;
      }
    case DECREMENTO:{
      jj_consume_token(DECREMENTO);
      break;
      }
    default:
      jj_la1[41] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PUNTO_Y_COMA);
}

  final public void IncrementoSentenciaSinPunto() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INCREMENTO:{
      jj_consume_token(INCREMENTO);
      break;
      }
    case DECREMENTO:{
      jj_consume_token(DECREMENTO);
      break;
      }
    default:
      jj_la1[42] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void Bloque() throws ParseException {
    jj_consume_token(LLAVE_APERTURA);
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CONST:
      case FOR:
      case FUNCTION:
      case IF:
      case RETURN:
      case VAR:
      case WHILE:
      case LET:
      case IDENTIFICADOR:
      case LLAVE_APERTURA:{
        ;
        break;
        }
      default:
        jj_la1[43] = jj_gen;
        break label_12;
      }
      Instruccion();
    }
    jj_consume_token(LLAVE_CIERRE);
}

  final public void LlamadaFuncion() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUNTO:{
        ;
        break;
        }
      default:
        jj_la1[44] = jj_gen;
        break label_13;
      }
      jj_consume_token(PUNTO);
      jj_consume_token(IDENTIFICADOR);
    }
    LlamadaArgumentos();
}

  final public void FuncionDeclaracion() throws ParseException {
    jj_consume_token(FUNCTION);
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(PARENTESIS_APERTURA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      Parametro();
      label_14:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMA:{
          ;
          break;
          }
        default:
          jj_la1[45] = jj_gen;
          break label_14;
        }
        jj_consume_token(COMA);
        Parametro();
      }
      break;
      }
    default:
      jj_la1[46] = jj_gen;
      ;
    }
    jj_consume_token(PARENTESIS_CIERRE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DOS_PUNTOS:{
      jj_consume_token(DOS_PUNTOS);
      Tipo();
      break;
      }
    default:
      jj_la1[47] = jj_gen;
      ;
    }
    Bloque();
}

  final public void ReturnSentencia() throws ParseException {
    jj_consume_token(RETURN);
    if (jj_2_8(1)) {
      Expresion();
    } else {
      ;
    }
    jj_consume_token(PUNTO_Y_COMA);
}

  final public void IfSentencia() throws ParseException {
    jj_consume_token(IF);
    jj_consume_token(PARENTESIS_APERTURA);
    Expresion();
    jj_consume_token(PARENTESIS_CIERRE);
    Bloque();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:{
        IfSentencia();
        break;
        }
      case LLAVE_APERTURA:{
        Bloque();
        break;
        }
      default:
        jj_la1[48] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[49] = jj_gen;
      ;
    }
}

  final public void ForInit() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LET:{
      jj_consume_token(LET);
      break;
      }
    case CONST:{
      jj_consume_token(CONST);
      break;
      }
    case VAR:{
      jj_consume_token(VAR);
      break;
      }
    default:
      jj_la1[50] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(IDENTIFICADOR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DOS_PUNTOS:{
      jj_consume_token(DOS_PUNTOS);
      Tipo();
      break;
      }
    default:
      jj_la1[51] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPERADOR_ASIGNACION:{
      jj_consume_token(OPERADOR_ASIGNACION);
      Expresion();
      break;
      }
    default:
      jj_la1[52] = jj_gen;
      ;
    }
}

  final public void ForSentencia() throws ParseException {
    jj_consume_token(FOR);
    jj_consume_token(PARENTESIS_APERTURA);
    if (siguienteEsForOf()) {
      ForInit();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OF:{
        jj_consume_token(OF);
        break;
        }
      case IN:{
        jj_consume_token(IN);
        break;
        }
      default:
        jj_la1[53] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Expresion();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CONST:
      case VAR:
      case LET:
      case PUNTO_Y_COMA:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CONST:
        case VAR:
        case LET:{
          ForInit();
          break;
          }
        default:
          jj_la1[54] = jj_gen;
          ;
        }
        jj_consume_token(PUNTO_Y_COMA);
        if (jj_2_9(1)) {
          Expresion();
        } else {
          ;
        }
        jj_consume_token(PUNTO_Y_COMA);
        if (jj_2_10(1)) {
          Expresion();
        } else {
          ;
        }
        break;
        }
      default:
        jj_la1[55] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(PARENTESIS_CIERRE);
    Sentencia();
}

  final public void WhileSentencia() throws ParseException {
    jj_consume_token(WHILE);
    jj_consume_token(PARENTESIS_APERTURA);
    Expresion();
    jj_consume_token(PARENTESIS_CIERRE);
    Sentencia();
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_10()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_3_3()
 {
    if (jj_3R_Expresion_294_3_16()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ArregloLiteral_355_39_63()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_Parametro_376_3_54()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(86)) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_Parametro_376_41_57()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_FlechaFuncion_371_5_53()
 {
    if (jj_scan_token(DOS_PUNTOS)) return true;
    return false;
  }

  private boolean jj_3R_Primario_339_35_46()
 {
    if (jj_3R_ArregloLiteral_355_3_50()) return true;
    return false;
  }

  private boolean jj_3R_FlechaFuncion_370_3_43()
 {
    if (jj_scan_token(PARENTESIS_APERTURA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_FlechaFuncion_370_27_52()) jj_scanpos = xsp;
    if (jj_scan_token(PARENTESIS_CIERRE)) return true;
    xsp = jj_scanpos;
    if (jj_3R_FlechaFuncion_371_5_53()) jj_scanpos = xsp;
    if (jj_scan_token(FLECHA)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_Expresion_294_3_16()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_LlamadaArgumentos_345_41_31()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_PropiedadObjeto_365_3_64()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(62)) {
    jj_scanpos = xsp;
    if (jj_scan_token(69)) return true;
    }
    xsp = jj_scanpos;
    if (jj_3R_PropiedadObjeto_365_36_66()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_ObjetoLiteral_360_3_51()
 {
    if (jj_scan_token(LLAVE_APERTURA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ObjetoLiteral_360_22_61()) jj_scanpos = xsp;
    if (jj_scan_token(LLAVE_CIERRE)) return true;
    return false;
  }

  private boolean jj_3R_Primario_337_23_56()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Primario_337_23_58()) {
    jj_scanpos = xsp;
    if (jj_3R_Primario_337_49_59()) {
    jj_scanpos = xsp;
    if (jj_3R_Primario_337_71_60()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_Primario_337_23_58()
 {
    if (jj_scan_token(PUNTO)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3R_ArregloLiteral_355_3_50()
 {
    if (jj_scan_token(CORCHETE_APERTURA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) jj_scanpos = xsp;
    if (jj_scan_token(CORCHETE_CIERRE)) return true;
    return false;
  }

  private boolean jj_3R_AccesoArreglo_350_3_62()
 {
    if (jj_scan_token(CORCHETE_APERTURA)) return true;
    if (jj_3R_Expresion_294_3_16()) return true;
    return false;
  }

  private boolean jj_3R_Valor_332_18_49()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(70)) {
    jj_scanpos = xsp;
    if (jj_scan_token(71)) return true;
    }
    return false;
  }

  private boolean jj_3R_LlamadaArgumentos_345_3_24()
 {
    if (jj_scan_token(PARENTESIS_APERTURA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) jj_scanpos = xsp;
    if (jj_scan_token(PARENTESIS_CIERRE)) return true;
    return false;
  }

  private boolean jj_3R_Primario_340_5_48()
 {
    if (jj_scan_token(PARENTESIS_APERTURA)) return true;
    if (jj_3R_Expresion_294_3_16()) return true;
    if (jj_scan_token(PARENTESIS_CIERRE)) return true;
    return false;
  }

  private boolean jj_3R_ExpresionRelacional_315_27_37()
 {
    if (jj_scan_token(OPERADOR_COMPARACION)) return true;
    if (jj_3R_ExpresionAritmetica_320_3_34()) return true;
    return false;
  }

  private boolean jj_3R_Primario_337_5_44()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Primario_337_5_45()) {
    jj_scanpos = xsp;
    if (jj_scan_token(68)) {
    jj_scanpos = xsp;
    if (jj_scan_token(67)) {
    jj_scanpos = xsp;
    if (jj_scan_token(66)) {
    jj_scanpos = xsp;
    if (jj_scan_token(63)) {
    jj_scanpos = xsp;
    if (jj_scan_token(64)) {
    jj_scanpos = xsp;
    if (jj_scan_token(65)) {
    jj_scanpos = xsp;
    if (jj_scan_token(69)) {
    jj_scanpos = xsp;
    if (jj_scan_token(50)) {
    jj_scanpos = xsp;
    if (jj_scan_token(51)) {
    jj_scanpos = xsp;
    if (jj_3R_Primario_339_35_46()) {
    jj_scanpos = xsp;
    if (jj_3R_Primario_339_54_47()) {
    jj_scanpos = xsp;
    if (jj_3R_Primario_340_5_48()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_Primario_337_5_45()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Primario_337_23_56()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_ExpresionLogica_310_27_35()
 {
    if (jj_scan_token(OPERADOR_LOGICO)) return true;
    if (jj_3R_ExpresionRelacional_315_3_32()) return true;
    return false;
  }

  private boolean jj_3R_Valor_332_5_42()
 {
    if (jj_3R_Primario_337_5_44()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Valor_332_18_49()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(86)) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_Valor_331_56_15()) jj_scanpos = xsp;
    if (jj_scan_token(FLECHA)) return true;
    if (jj_3R_Expresion_294_3_16()) return true;
    return false;
  }

  private boolean jj_3R_Valor_330_5_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    jj_lookingAhead = true;
    jj_semLA = siguienteEsFlecha();
    jj_lookingAhead = false;
    if (!jj_semLA || jj_3R_Valor_330_5_41()) {
    jj_scanpos = xsp;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3R_Valor_332_5_42()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_Valor_330_5_41()
 {
    if (jj_3R_FlechaFuncion_370_3_43()) return true;
    return false;
  }

  private boolean jj_3R_ExpresionAritmetica_320_14_40()
 {
    if (jj_scan_token(OPERADOR_ARITMETICO)) return true;
    if (jj_3R_Factor_325_3_36()) return true;
    return false;
  }

  private boolean jj_3R_Factor_325_5_38()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(74)) {
    jj_scanpos = xsp;
    if (jj_scan_token(75)) return true;
    }
    return false;
  }

  private boolean jj_3R_Factor_325_3_36()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Factor_325_5_38()) jj_scanpos = xsp;
    if (jj_3R_Valor_330_5_39()) return true;
    return false;
  }

  private boolean jj_3R_ExpresionTernaria_305_23_33()
 {
    if (jj_scan_token(INTERROGACION)) return true;
    if (jj_3R_Expresion_294_3_16()) return true;
    return false;
  }

  private boolean jj_3_10()
 {
    if (jj_3R_Expresion_294_3_16()) return true;
    return false;
  }

  private boolean jj_3R_ExpresionAritmetica_320_3_34()
 {
    if (jj_3R_Factor_325_3_36()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ExpresionAritmetica_320_14_40()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_ExpresionRelacional_315_3_32()
 {
    if (jj_3R_ExpresionAritmetica_320_3_34()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ExpresionRelacional_315_27_37()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_ExpresionLogica_310_3_29()
 {
    if (jj_3R_ExpresionRelacional_315_3_32()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ExpresionLogica_310_27_35()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_ExpresionTernaria_305_3_27()
 {
    if (jj_3R_ExpresionLogica_310_3_29()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ExpresionTernaria_305_23_33()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_ExpresionAsignacion_300_5_30()
 {
    if (jj_scan_token(OPERADOR_ASIGNACION)) return true;
    if (jj_3R_ExpresionAsignacion_299_3_21()) return true;
    return false;
  }

  private boolean jj_3R_ExpresionAsignacion_299_3_21()
 {
    if (jj_3R_ExpresionTernaria_305_3_27()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ExpresionAsignacion_300_5_30()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_Expresion_294_3_16()
 {
    if (jj_3R_ExpresionAsignacion_299_3_21()) return true;
    return false;
  }

  private boolean jj_3_9()
 {
    if (jj_3R_Expresion_294_3_16()) return true;
    return false;
  }

  private boolean jj_3R_TipoBase_287_5_28()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(55)) {
    jj_scanpos = xsp;
    if (jj_scan_token(57)) {
    jj_scanpos = xsp;
    if (jj_scan_token(56)) {
    jj_scanpos = xsp;
    if (jj_scan_token(54)) {
    jj_scanpos = xsp;
    if (jj_scan_token(60)) {
    jj_scanpos = xsp;
    if (jj_scan_token(59)) {
    jj_scanpos = xsp;
    if (jj_scan_token(61)) {
    jj_scanpos = xsp;
    if (jj_scan_token(37)) {
    jj_scanpos = xsp;
    if (jj_scan_token(62)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_Tipo_282_5_26()
 {
    if (jj_scan_token(CORCHETE_APERTURA)) return true;
    return false;
  }

  private boolean jj_3R_Tipo_281_3_25()
 {
    if (jj_3R_TipoBase_287_5_28()) return true;
    return false;
  }

  private boolean jj_3R_Tipo_281_3_20()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Tipo_281_3_25()) {
    jj_scanpos = xsp;
    if (jj_3R_Tipo_282_5_26()) return true;
    }
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_3R_Expresion_294_3_16()) return true;
    return false;
  }

  private boolean jj_3R_LlamadaFuncion_421_21_23()
 {
    if (jj_scan_token(PUNTO)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3R_LlamadaFuncion_421_3_19()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_LlamadaFuncion_421_21_23()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_LlamadaArgumentos_345_3_24()) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_Expresion_294_3_16()) return true;
    return false;
  }

  private boolean jj_3R_Parametro_376_41_57()
 {
    if (jj_scan_token(DOS_PUNTOS)) return true;
    return false;
  }

  private boolean jj_3R_Asignacion_391_21_22()
 {
    if (jj_scan_token(PUNTO)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3R_FlechaFuncion_370_41_55()
 {
    if (jj_scan_token(COMA)) return true;
    return false;
  }

  private boolean jj_3R_IncrementoSentencia_406_3_18()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(70)) {
    jj_scanpos = xsp;
    if (jj_scan_token(71)) return true;
    }
    if (jj_scan_token(PUNTO_Y_COMA)) return true;
    return false;
  }

  private boolean jj_3R_Primario_337_71_60()
 {
    if (jj_3R_AccesoArreglo_350_3_62()) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_LlamadaFuncion_421_3_19()) return true;
    if (jj_scan_token(PUNTO_Y_COMA)) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_3R_IncrementoSentencia_406_3_18()) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_Asignacion_391_3_17()) return true;
    return false;
  }

  private boolean jj_3R_ObjetoLiteral_360_42_65()
 {
    if (jj_scan_token(COMA)) return true;
    return false;
  }

  private boolean jj_3R_PropiedadObjeto_365_36_66()
 {
    if (jj_scan_token(DOS_PUNTOS)) return true;
    return false;
  }

  private boolean jj_3R_FlechaFuncion_370_27_52()
 {
    if (jj_3R_Parametro_376_3_54()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_FlechaFuncion_370_41_55()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_Asignacion_391_3_17()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Asignacion_391_21_22()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(OPERADOR_ASIGNACION)) return true;
    if (jj_3R_Expresion_294_3_16()) return true;
    if (jj_scan_token(PUNTO_Y_COMA)) return true;
    return false;
  }

  private boolean jj_3R_ArregloLiteral_355_39_63()
 {
    if (jj_scan_token(COMA)) return true;
    return false;
  }

  private boolean jj_3R_Primario_339_54_47()
 {
    if (jj_3R_ObjetoLiteral_360_3_51()) return true;
    return false;
  }

  private boolean jj_3R_Valor_331_56_15()
 {
    if (jj_scan_token(DOS_PUNTOS)) return true;
    if (jj_3R_Tipo_281_3_20()) return true;
    return false;
  }

  private boolean jj_3R_LlamadaArgumentos_345_41_31()
 {
    if (jj_scan_token(COMA)) return true;
    return false;
  }

  private boolean jj_3R_Primario_337_49_59()
 {
    if (jj_3R_LlamadaArgumentos_345_3_24()) return true;
    return false;
  }

  private boolean jj_3R_ObjetoLiteral_360_22_61()
 {
    if (jj_3R_PropiedadObjeto_365_3_64()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ObjetoLiteral_360_42_65()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_scan_token(83)) jj_scanpos = xsp;
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[56];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x800,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x21c00800,0x0,0x21400000,0x0,0x0,0x21c00800,0x0,0x0,0x0,0x0,0x1000000,0x20000,0x800,0x0,0x0,0x4000000,0x800,0x800,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x110,0x0,0x0,0x0,0x0,0x0,0x0,0x7bc00020,0x7bc00020,0x7bc00020,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xc00c0000,0x0,0x0,0xc00c0000,0x0,0x0,0x0,0x0,0x40000000,0x40000000,0x0,0x0,0x40000000,0x0,0x0,0x0,0x0,0x40000150,0x0,0x40,0x0,0x0,0x40000150,0x0,0x0,0x40000000,0x0,0x0,0x0,0x110,0x0,0x0,0x100000,0x110,0x110,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x400000,0x200000,0x100,0x40000,0x4000,0x80000,0x4000,0x4000,0x0,0x100,0x400000,0x400,0x200,0x800,0xc00,0xc00,0x400000,0x200000,0xc0,0xc0,0x1503f,0x105000,0x105000,0x1503f,0x80000,0x80000,0x80000,0x80000,0x20,0x20,0x200000,0x80000,0x0,0x200000,0x10000,0x400000,0x200000,0x10000,0x100000,0x10000,0xc0,0xc0,0x10000,0x100000,0x80000,0x0,0x200000,0x10000,0x0,0x0,0x200000,0x100,0x0,0x0,0x40000,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[10];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 56; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 56; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 56; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new ParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 56; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 56; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 56; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = jj_lookingAhead ? jj_scanpos : token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[88];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 56; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 88; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 10; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			   case 9: jj_3_10(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
