/* ParserTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. ParserTokenManager.java */
package main;

/** Token Manager. */
public class ParserTokenManager implements ParserConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 20);
      case 41:
         return jjStopAtPos(0, 21);
      case 44:
         return jjStopAtPos(0, 27);
      case 46:
         return jjStopAtPos(0, 28);
      case 58:
         return jjStopAtPos(0, 29);
      case 59:
         return jjStopAtPos(0, 26);
      case 63:
         return jjStartNfaWithStates_0(0, 30, 38);
      case 91:
         return jjStopAtPos(0, 22);
      case 93:
         return jjStopAtPos(0, 23);
      case 123:
         return jjStopAtPos(0, 24);
      case 125:
         return jjStopAtPos(0, 25);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 354;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff009cffffd9ffL & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                  }
                  else if ((0xac6000000000L & l) != 0L)
                  {
                     if (kind > 19)
                        kind = 19;
                  }
                  else if ((0x5000000000000000L & l) != 0L)
                  {
                     if (kind > 17)
                        kind = 17;
                  }
                  else if (curChar == 33)
                     { jjCheckNAddTwoStates(78, 75); }
                  else if (curChar == 61)
                     { jjCheckNAddTwoStates(76, 75); }
                  else if (curChar == 63)
                     { jjCheckNAdd(38); }
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(0, 13); }
                  else if (curChar == 42)
                     { jjCheckNAddStates(14, 16); }
                  else if (curChar == 60)
                     { jjCheckNAddTwoStates(75, 350); }
                  else if (curChar == 62)
                     { jjCheckNAddStates(17, 19); }
                  else if (curChar == 45)
                     { jjCheckNAddTwoStates(20, 345); }
                  else if (curChar == 43)
                     { jjCheckNAddTwoStates(20, 343); }
                  else if (curChar == 39)
                  {
                     if (kind > 31)
                        kind = 31;
                     { jjCheckNAddStates(20, 23); }
                  }
                  else if (curChar == 34)
                  {
                     if (kind > 31)
                        kind = 31;
                     { jjCheckNAddStates(24, 27); }
                  }
                  else if (curChar == 36)
                  {
                     if (kind > 8)
                        kind = 8;
                     { jjCheckNAddStates(28, 34); }
                  }
                  else if (curChar == 47)
                     { jjCheckNAddTwoStates(288, 20); }
                  else if (curChar == 33)
                  {
                     if (kind > 18)
                        kind = 18;
                  }
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 24;
                  else if (curChar == 61)
                  {
                     if (kind > 16)
                        kind = 16;
                  }
                  else if (curChar == 37)
                     { jjCheckNAdd(20); }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 14)
                        kind = 14;
                     { jjCheckNAddStates(35, 41); }
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 14)
                        kind = 14;
                     { jjCheckNAddStates(42, 47); }
                  }
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(2, 3); }
                  break;
               case 2:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(2, 3); }
                  break;
               case 3:
                  if (curChar == 42)
                     { jjAddStates(48, 49); }
                  break;
               case 4:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(2, 3); }
                  break;
               case 5:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 20:
                  if (curChar == 61 && kind > 16)
                     kind = 16;
                  break;
               case 21:
                  if (curChar == 37)
                     { jjCheckNAdd(20); }
                  break;
               case 22:
                  if (curChar == 61 && kind > 16)
                     kind = 16;
                  break;
               case 23:
                  if ((0x5000000000000000L & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 24:
                  if (curChar == 38 && kind > 18)
                     kind = 18;
                  break;
               case 25:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 28:
                  if (curChar == 33 && kind > 18)
                     kind = 18;
                  break;
               case 29:
                  if ((0xac6000000000L & l) != 0L && kind > 19)
                     kind = 19;
                  break;
               case 31:
                  if (curChar == 36)
                     { jjCheckNAddTwoStates(32, 33); }
                  break;
               case 32:
                  if ((0x3ff001000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(32, 33); }
                  break;
               case 35:
                  if (curChar != 36)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(36); }
                  break;
               case 36:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(36); }
                  break;
               case 37:
                  if (curChar == 63)
                     { jjCheckNAdd(38); }
                  break;
               case 38:
                  if (curChar != 63)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAddTwoStates(38, 39); }
                  break;
               case 39:
                  if ((0xfffffffeffffd9ffL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(39); }
                  break;
               case 40:
                  if ((0x3ff009cffffd9ffL & l) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(0, 13); }
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(42, 43); }
                  break;
               case 43:
                  if ((0xf000ac6200000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(44); }
                  break;
               case 44:
                  if ((0xfffffffeffffd9ffL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(44); }
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(45, 46); }
                  break;
               case 47:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(48); }
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(48, 49); }
                  break;
               case 49:
                  if (curChar == 46)
                     { jjCheckNAdd(50); }
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAddTwoStates(50, 51); }
                  break;
               case 51:
                  if ((0xfffffffeffffd9ffL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(51); }
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(52, 53); }
                  break;
               case 53:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 54:
                  if (curChar != 36)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(55); }
                  break;
               case 55:
                  if ((0xfffffffeffffd9ffL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(55); }
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(56, 57); }
                  break;
               case 57:
                  if (curChar == 46)
                     { jjCheckNAddTwoStates(58, 59); }
                  break;
               case 58:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(58, 59); }
                  break;
               case 59:
                  if ((0x500000000000L & l) != 0L)
                     { jjCheckNAdd(60); }
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(60); }
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(61, 62); }
                  break;
               case 62:
                  if (curChar != 36)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(63); }
                  break;
               case 63:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(63); }
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(64, 65); }
                  break;
               case 65:
                  if (curChar == 46)
                     { jjCheckNAddTwoStates(66, 67); }
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(66, 67); }
                  break;
               case 67:
                  if (curChar == 46)
                     { jjCheckNAdd(68); }
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAddTwoStates(67, 68); }
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(69, 70); }
                  break;
               case 70:
                  if (curChar == 46)
                     { jjCheckNAdd(71); }
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(71, 72); }
                  break;
               case 72:
                  if ((0xac0000000000L & l) != 0L)
                     { jjCheckNAdd(73); }
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(73); }
                  break;
               case 74:
                  if (curChar == 61)
                     { jjCheckNAddTwoStates(76, 75); }
                  break;
               case 75:
                  if (curChar == 61 && kind > 17)
                     kind = 17;
                  break;
               case 76:
               case 78:
                  if (curChar == 61)
                     { jjCheckNAdd(75); }
                  break;
               case 77:
                  if (curChar == 33)
                     { jjCheckNAddTwoStates(78, 75); }
                  break;
               case 287:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(288, 20); }
                  break;
               case 288:
                  if (curChar != 47)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAddStates(50, 52); }
                  break;
               case 289:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAddStates(50, 52); }
                  break;
               case 290:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 291:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 290;
                  break;
               case 292:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 293:
                  if (curChar != 36)
                     break;
                  if (kind > 8)
                     kind = 8;
                  { jjCheckNAddStates(28, 34); }
                  break;
               case 294:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  { jjCheckNAdd(294); }
                  break;
               case 295:
                  if ((0x3ff001000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(295, 296); }
                  break;
               case 296:
                  if ((0xf000ac6a00000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(297); }
                  break;
               case 297:
                  if ((0xfffffffeffffd9ffL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(297); }
                  break;
               case 298:
                  if ((0x3ff001000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(298, 299); }
                  break;
               case 299:
                  if (curChar == 63)
                     { jjCheckNAdd(300); }
                  break;
               case 300:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(300); }
                  break;
               case 301:
                  if ((0x3ff001000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(301, 302); }
                  break;
               case 302:
                  if ((0xf000ac6200000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 303:
                  if ((0xf000ac6200000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(304); }
                  break;
               case 304:
                  if ((0xfffffffeffffd9ffL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(304); }
                  break;
               case 305:
                  if (curChar != 48)
                     break;
                  if (kind > 14)
                     kind = 14;
                  { jjCheckNAddStates(42, 47); }
                  break;
               case 307:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjstateSet[jjnewStateCnt++] = 307;
                  break;
               case 309:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjstateSet[jjnewStateCnt++] = 309;
                  break;
               case 311:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjstateSet[jjnewStateCnt++] = 311;
                  break;
               case 312:
                  if (curChar == 46)
                     { jjCheckNAdd(313); }
                  break;
               case 313:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(313, 314); }
                  break;
               case 315:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(316); }
                  break;
               case 316:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  { jjCheckNAdd(316); }
                  break;
               case 317:
                  if (curChar == 46)
                     { jjCheckNAdd(318); }
                  break;
               case 318:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  { jjCheckNAdd(318); }
                  break;
               case 319:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  { jjCheckNAddStates(35, 41); }
                  break;
               case 320:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(320, 312); }
                  break;
               case 321:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(321, 314); }
                  break;
               case 322:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(322, 317); }
                  break;
               case 323:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  { jjCheckNAdd(323); }
                  break;
               case 324:
                  if (curChar != 34)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAddStates(24, 27); }
                  break;
               case 326:
                  { jjCheckNAddStates(53, 55); }
                  break;
               case 327:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddStates(53, 55); }
                  break;
               case 328:
                  if (curChar == 34 && kind > 15)
                     kind = 15;
                  break;
               case 329:
                  if ((0xfffffffbffffdbffL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(329); }
                  break;
               case 330:
                  if (curChar != 39)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAddStates(20, 23); }
                  break;
               case 332:
                  { jjCheckNAddStates(56, 58); }
                  break;
               case 333:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     { jjCheckNAddStates(56, 58); }
                  break;
               case 334:
                  if (curChar == 39 && kind > 15)
                     kind = 15;
                  break;
               case 335:
                  if ((0xffffff7fffffdbffL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(335); }
                  break;
               case 338:
               case 339:
                  { jjCheckNAddStates(59, 61); }
                  break;
               case 341:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 341;
                  break;
               case 342:
                  if (curChar == 43)
                     { jjCheckNAddTwoStates(20, 343); }
                  break;
               case 343:
                  if (curChar == 43 && kind > 19)
                     kind = 19;
                  break;
               case 344:
                  if (curChar == 45)
                     { jjCheckNAddTwoStates(20, 345); }
                  break;
               case 345:
                  if (curChar == 45 && kind > 19)
                     kind = 19;
                  break;
               case 346:
                  if (curChar == 62)
                     { jjCheckNAddStates(17, 19); }
                  break;
               case 347:
                  if (curChar == 62 && kind > 19)
                     kind = 19;
                  break;
               case 348:
                  if (curChar == 62)
                     { jjCheckNAdd(347); }
                  break;
               case 349:
                  if (curChar == 60)
                     { jjCheckNAddTwoStates(75, 350); }
                  break;
               case 350:
                  if (curChar == 60 && kind > 19)
                     kind = 19;
                  break;
               case 351:
                  if (curChar == 42)
                     { jjCheckNAddStates(14, 16); }
                  break;
               case 352:
                  if (curChar == 42)
                     { jjCheckNAdd(20); }
                  break;
               case 353:
                  if (curChar == 42 && kind > 19)
                     kind = 19;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x87ffffff97ffffffL & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                  }
                  else if ((0x5000000040000000L & l) != 0L)
                  {
                     if (kind > 19)
                        kind = 19;
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 8)
                        kind = 8;
                     { jjCheckNAddStates(28, 34); }
                  }
                  else if (curChar == 96)
                  {
                     if (kind > 31)
                        kind = 31;
                     { jjCheckNAddStates(62, 65); }
                  }
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 35;
                  else if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 31;
                  if (curChar == 117)
                     { jjAddStates(66, 67); }
                  else if (curChar == 112)
                     { jjAddStates(68, 71); }
                  else if (curChar == 97)
                     { jjAddStates(72, 73); }
                  else if (curChar == 119)
                     { jjAddStates(74, 75); }
                  else if (curChar == 118)
                     { jjAddStates(76, 77); }
                  else if (curChar == 116)
                     { jjAddStates(78, 82); }
                  else if (curChar == 115)
                     { jjAddStates(83, 87); }
                  else if (curChar == 110)
                     { jjAddStates(88, 91); }
                  else if (curChar == 105)
                     { jjCheckNAddStates(92, 97); }
                  else if (curChar == 102)
                     { jjAddStates(98, 101); }
                  else if (curChar == 101)
                     { jjAddStates(102, 105); }
                  else if (curChar == 100)
                     { jjAddStates(106, 109); }
                  else if (curChar == 99)
                     { jjAddStates(110, 114); }
                  else if (curChar == 98)
                     { jjAddStates(115, 116); }
                  else if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 26;
                  else if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 18;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 13;
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 2:
               case 4:
                  { jjCheckNAddTwoStates(2, 3); }
                  break;
               case 6:
                  if (curChar == 110 && kind > 7)
                     kind = 7;
                  break;
               case 7:
                  if (curChar == 114)
                     { jjCheckNAdd(6); }
                  break;
               case 8:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 116 && kind > 7)
                     kind = 7;
                  break;
               case 13:
                  if (curChar == 101)
                     { jjCheckNAdd(12); }
                  break;
               case 14:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 100 && kind > 7)
                     kind = 7;
                  break;
               case 16:
                  if (curChar == 108)
                     { jjCheckNAdd(15); }
                  break;
               case 17:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 26:
                  if (curChar == 124 && kind > 18)
                     kind = 18;
                  break;
               case 27:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 29:
                  if ((0x5000000040000000L & l) != 0L && kind > 19)
                     kind = 19;
                  break;
               case 30:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
               case 32:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(32, 33); }
                  break;
               case 33:
                  if (curChar == 124 && kind > 31)
                     kind = 31;
                  break;
               case 34:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
               case 36:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(36); }
                  break;
               case 39:
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 40:
                  if ((0x87ffffff97ffffffL & l) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 43:
                  if ((0x5000000040000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(44); }
                  break;
               case 44:
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(44); }
                  break;
               case 46:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(117, 118); }
                  break;
               case 51:
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 54:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(55); }
                  break;
               case 55:
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(55); }
                  break;
               case 62:
               case 63:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(63); }
                  break;
               case 79:
                  if (curChar == 98)
                     { jjAddStates(115, 116); }
                  break;
               case 80:
                  if (curChar == 107 && kind > 7)
                     kind = 7;
                  break;
               case 81:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (curChar == 97)
                     { jjCheckNAdd(6); }
                  break;
               case 85:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 99)
                     { jjAddStates(110, 114); }
                  break;
               case 90:
                  if (curChar == 101 && kind > 7)
                     kind = 7;
                  break;
               case 91:
               case 129:
               case 144:
                  if (curChar == 115)
                     { jjCheckNAdd(90); }
                  break;
               case 92:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 104 && kind > 7)
                     kind = 7;
                  break;
               case 94:
               case 206:
                  if (curChar == 99)
                     { jjCheckNAdd(93); }
                  break;
               case 95:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 115 && kind > 7)
                     kind = 7;
                  break;
               case 98:
                  if (curChar == 115)
                     { jjCheckNAdd(97); }
                  break;
               case 99:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 115)
                     { jjCheckNAdd(12); }
                  break;
               case 102:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
               case 230:
                  if (curChar == 117)
                     { jjCheckNAdd(90); }
                  break;
               case 105:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if (curChar == 100)
                     { jjAddStates(106, 109); }
                  break;
               case 111:
                  if (curChar == 114 && kind > 7)
                     kind = 7;
                  break;
               case 112:
               case 195:
               case 199:
               case 203:
                  if (curChar == 101)
                     { jjCheckNAdd(111); }
                  break;
               case 113:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 116:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 108)
                     { jjCheckNAdd(12); }
                  break;
               case 119:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
               case 258:
                  if (curChar == 116)
                     { jjCheckNAdd(90); }
                  break;
               case 124:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 126:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 111 && kind > 7)
                     kind = 7;
                  break;
               case 128:
                  if (curChar == 101)
                     { jjAddStates(102, 105); }
                  break;
               case 130:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 109 && kind > 7)
                     kind = 7;
                  break;
               case 132:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
               case 162:
                  if (curChar == 114)
                     { jjCheckNAdd(12); }
                  break;
               case 135:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 136:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 137:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 100)
                     { jjCheckNAdd(97); }
                  break;
               case 139:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 140:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 102)
                     { jjAddStates(98, 101); }
                  break;
               case 145:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 121 && kind > 7)
                     kind = 7;
                  break;
               case 148:
                  if (curChar == 108)
                     { jjCheckNAdd(147); }
                  break;
               case 149:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 153:
                  if (curChar == 111)
                     { jjCheckNAdd(111); }
                  break;
               case 154:
                  if (curChar == 111)
                     { jjCheckNAdd(6); }
                  break;
               case 155:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 157:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 158:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 159:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 160:
                  if (curChar == 105)
                     { jjCheckNAddStates(92, 97); }
                  break;
               case 161:
                  if (curChar == 102 && kind > 7)
                     kind = 7;
                  break;
               case 163:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
               case 233:
                  if (curChar == 111)
                     { jjCheckNAdd(161); }
                  break;
               case 167:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 168:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 171:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 172:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if (curChar == 99)
                     { jjCheckNAdd(90); }
                  break;
               case 175:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 177:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 178:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 180:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 181:
                  if (curChar == 116)
                     { jjCheckNAdd(97); }
                  break;
               case 182:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 183:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 182;
                  break;
               case 184:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 185:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 186:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 187:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 188:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 189:
                  if (curChar == 110)
                     { jjAddStates(88, 91); }
                  break;
               case 190:
                  if (curChar == 119 && kind > 7)
                     kind = 7;
                  break;
               case 191:
                  if (curChar == 101)
                     { jjCheckNAdd(190); }
                  break;
               case 192:
                  if (curChar == 108 && kind > 7)
                     kind = 7;
                  break;
               case 193:
                  if (curChar == 108)
                     { jjCheckNAdd(192); }
                  break;
               case 194:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 196:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 197:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 198:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 197;
                  break;
               case 200:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 201:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if (curChar == 115)
                     { jjAddStates(83, 87); }
                  break;
               case 204:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 205:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 207:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 206;
                  break;
               case 208:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if (curChar == 99 && kind > 7)
                     kind = 7;
                  break;
               case 211:
               case 270:
                  if (curChar == 105)
                     { jjCheckNAdd(210); }
                  break;
               case 212:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 211;
                  break;
               case 213:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 212;
                  break;
               case 214:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 215:
                  if (curChar == 103 && kind > 7)
                     kind = 7;
                  break;
               case 216:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 215;
                  break;
               case 217:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 218:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 219:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 220:
                  if (curChar == 111)
                     { jjCheckNAdd(192); }
                  break;
               case 221:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 224:
                  if (curChar == 116)
                     { jjAddStates(78, 82); }
                  break;
               case 225:
                  if (curChar == 105)
                     { jjCheckNAdd(97); }
                  break;
               case 226:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if (curChar == 111)
                     { jjCheckNAdd(190); }
                  break;
               case 228:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 231:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 232:
                  if (curChar == 114)
                     { jjCheckNAdd(147); }
                  break;
               case 234:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 236:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if (curChar == 118)
                     { jjAddStates(76, 77); }
                  break;
               case 238:
                  if (curChar == 97)
                     { jjCheckNAdd(111); }
                  break;
               case 239:
                  if (curChar == 105)
                     { jjCheckNAdd(15); }
                  break;
               case 240:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 241:
                  if (curChar == 119)
                     { jjAddStates(74, 75); }
                  break;
               case 242:
                  if (curChar == 108)
                     { jjCheckNAdd(90); }
                  break;
               case 243:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 244:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 245:
                  if (curChar == 116)
                     { jjCheckNAdd(93); }
                  break;
               case 246:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 97)
                     { jjAddStates(72, 73); }
                  break;
               case 248:
                  if (curChar == 105)
                     { jjCheckNAdd(12); }
                  break;
               case 249:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 250:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 249;
                  break;
               case 251:
                  if (curChar == 110)
                     { jjCheckNAdd(147); }
                  break;
               case 252:
                  if (curChar == 112)
                     { jjAddStates(68, 71); }
                  break;
               case 253:
                  if (curChar == 103)
                     { jjCheckNAdd(90); }
                  break;
               case 254:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 255:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 256:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 257:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 259:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 260:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 261:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 262:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 261;
                  break;
               case 263:
               case 280:
                  if (curChar == 101)
                     { jjCheckNAdd(15); }
                  break;
               case 264:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 265:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 264;
                  break;
               case 266:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 267:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 268:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 269:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 271:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 272:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 271;
                  break;
               case 273:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 274:
                  if (curChar == 117)
                     { jjAddStates(66, 67); }
                  break;
               case 275:
                  if (curChar == 119)
                     { jjCheckNAdd(6); }
                  break;
               case 276:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 277:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 278:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 279:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 281:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 282:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 283:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 284:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 285:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 286:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 289:
                  if (kind > 5)
                     kind = 5;
                  { jjAddStates(50, 52); }
                  break;
               case 293:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  { jjCheckNAddStates(28, 34); }
                  break;
               case 294:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  { jjCheckNAdd(294); }
                  break;
               case 295:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(295, 296); }
                  break;
               case 296:
                  if ((0x5000000040000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(297); }
                  break;
               case 297:
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(297); }
                  break;
               case 298:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(298, 299); }
                  break;
               case 300:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 300;
                  break;
               case 301:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(301, 302); }
                  break;
               case 302:
                  if ((0x5000000040000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 303:
                  if ((0x5000000040000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(304); }
                  break;
               case 304:
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(304); }
                  break;
               case 306:
                  if ((0x100000001000000L & l) != 0L)
                     { jjCheckNAdd(307); }
                  break;
               case 307:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAdd(307); }
                  break;
               case 308:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 309;
                  break;
               case 310:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 311;
                  break;
               case 314:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(119, 120); }
                  break;
               case 325:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 326;
                  break;
               case 326:
                  { jjCheckNAddStates(53, 55); }
                  break;
               case 327:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(53, 55); }
                  break;
               case 329:
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 329;
                  break;
               case 331:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 332;
                  break;
               case 332:
                  { jjCheckNAddStates(56, 58); }
                  break;
               case 333:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(56, 58); }
                  break;
               case 335:
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 335;
                  break;
               case 336:
                  if (curChar != 96)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAddStates(62, 65); }
                  break;
               case 337:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 338;
                  break;
               case 338:
                  { jjCheckNAddStates(59, 61); }
                  break;
               case 339:
                  if ((0xfffffffeefffffffL & l) != 0L)
                     { jjCheckNAddStates(59, 61); }
                  break;
               case 340:
                  if (curChar == 96 && kind > 15)
                     kind = 15;
                  break;
               case 341:
                  if ((0xfffffffeffffffffL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  { jjCheckNAdd(341); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((jjbitVec0[i2] & l2) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 2:
               case 4:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(2, 3); }
                  break;
               case 39:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 44:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 51:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 55:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 289:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjAddStates(50, 52); }
                  break;
               case 297:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 297;
                  break;
               case 304:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 326:
               case 327:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(53, 55); }
                  break;
               case 329:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 329;
                  break;
               case 332:
               case 333:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(56, 58); }
                  break;
               case 335:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 335;
                  break;
               case 338:
               case 339:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(59, 61); }
                  break;
               case 341:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjstateSet[jjnewStateCnt++] = 341;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 354 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, "\50", "\51", "\133", "\135", "\173", 
"\175", "\73", "\54", "\56", "\72", "\77", null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   42, 43, 45, 46, 52, 53, 56, 57, 61, 62, 64, 65, 69, 70, 352, 20, 
   353, 75, 348, 347, 331, 333, 334, 335, 325, 327, 328, 329, 294, 295, 296, 298, 
   299, 301, 302, 320, 312, 321, 314, 322, 317, 323, 306, 308, 310, 312, 314, 317, 
   4, 5, 289, 291, 292, 325, 327, 328, 331, 333, 334, 337, 339, 340, 337, 339, 
   340, 341, 279, 286, 257, 262, 269, 273, 250, 251, 244, 246, 238, 240, 226, 229, 
   231, 232, 236, 205, 209, 214, 219, 223, 191, 194, 198, 201, 161, 165, 6, 173, 
   180, 188, 146, 152, 153, 159, 130, 133, 137, 142, 117, 122, 126, 127, 92, 96, 
   100, 103, 109, 83, 88, 47, 48, 315, 316, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public ParserTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public ParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 354; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffff81L, 
};
static final long[] jjtoSkip = {
   0x7eL, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[354];
    private final int[] jjstateSet = new int[2 * 354];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
